WFinanciera/urls.py
from django.contrib import admin
from django.http import HttpRequest
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from apps.usuario import views as views_root

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sobre-nosotros/', views_root.about, name='about'),
    path('', views_root.home, name='inicio'),
    path('partners/', include('apps.socios.urls')),
    path('loans/', include('apps.prestamos.urls')),
    path('accounts/', include('apps.usuario.urls')),
]

apps/socios/urls.py
from django.urls import path
from .views import (
    SocioCreateView,
    SocioDetailView,
    SocioListView,
    SocioEditView,
    SocioDeleteView,
    AccountBankDetailView,
    search_partners,
)

app_name = 'socio'
urlpatterns = [
    path('create-partner/', SocioCreateView.as_view(), name='crearsocio'),
    path('lists-partners/', SocioListView.as_view(), name='listasocio'),
    path('edit-partner/<int:pk>', SocioEditView.as_view(), name='editarsocio'),
    path('delete-partner/<int:pk>',
         SocioDeleteView.as_view(), name='eliminarsocio'),
    path('detail-partner/<int:pk>', SocioDetailView.as_view(), name='detallesocio'),
    path('<int:pk>/account-partner/',
         AccountBankDetailView.as_view(), name='account_bank'),
    path('search-partners/', search_partners, name='search-partners')
]

apps/usuario/urls.py
from django.urls import path
from .views import AccountDetailView, LoginFormView, logout_usuario

app_name = 'usuario'
urlpatterns = [
	path('partners/<int:pk>/', AccountDetailView.as_view(), name='perfilusuario'),
	path('partners/login/',LoginFormView.as_view(), name='login'),
	path('partners/logout/', logout_usuario, name='logout'),
]

templates/base/_head.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="description" content="Cooperativa de Ahorro y Credito Wiñarisun">
<script type="text/javascript" src="{% static 'js/jquery.js' %}" defer></script>
<script type="text/javascript" src="{% static 'js/popper.js' %}" defer></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}" defer></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}" defer></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}" defer></script>
<link rel="shortcut icon" href="{% static 'img/cw2.ico' %}" class="shortcut">
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'css/button_style.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'css/word.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'css/boderstyle.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'css/icons_social.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'css/estilos_contactos.css' %}" type="text/css">
<title>Wiñarisun | {% block titulo %}Cooperativa de Ahorro y Crédito{% endblock titulo %}</title>

templates/base/_nabvar.html
{% load static %}
<div class="fixed-top fixed-top-sticky">
  {% block menu %}
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'inicio' %}"><img class="navbar-brand" src="{% static 'img/cw1.jpg' %}"
                                                           width="150px" height="70px"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHomeMain"
            aria-controls="navbarHomeMain" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarHomeMain">
      <ul class="navbar-nav mr-auto">
        <li class="button nav-item">
          <a class="nav-link1 font-weight-bold" href="{% url 'inicio'%}">Inicio</a>
        </li>
        <li class="button nav-item dropdown">
          <a class="nav-link1 font-weight-bold dropdown-toggle" data-toggle="dropdown" id="navbardrop"
             href="#">Prestamos</a>
          <div class="dropdown-menu border-0 ">
            <a href="#" class="dropdown-item text-body">De acuerdo a su necesidad</a>
            <hr class="line_separate">
            <a href="#" class="dropdown-item text-body">Con una tasa de ínteres moderada</a>
            <hr class="line_separate">
            <a href="#" class="dropdown-item text-body">A plazo fijo</a>
            <hr class="line_separate">
          </div>
        </li>
        <li class="button nav-item">
          <a class="nav-link1 font-weight-bold" href="#">Atenciones</a>
        </li>
        <li class="button nav-item" data-toggle="modal" data-target="#modal-search">
          <a class="nav-link1 font-weight-bold" href="#">Acerca de</a>
        </li>
        <li class="button nav-item" data-toggle="modal" data-target="#modal-email">
          <a class="nav-link1 font-weight-bold" href="#">Enviar Mensaje</a>
        </li>
      </ul>
      <div class="my-2 my-lg-0 ">
        {% if user.is_authenticated %}
        <div class="btn-group">
          <button type="button" class="button type1 dropdown-toggle ml-2" data-toggle="dropdown" aria-haspopup="true"
                  aria-expanded="false">
            {% if user.is_staff %}
            <strong>{{ user.username }}</strong>
            {% else %}
            <strong>{{ user.socio.nombre }} {{ user.socio.apellido_paterno }}
              {{ user.socio.apellido_materno }}</strong>
            {% endif %}
          </button>
          <div class="dropdown-menu dropdown-menu-right mr-0">
            <a href="{% url 'usuario:perfilusuario' request.user.id %}" class="dropdown-item">Mi Cuenta</a>
            {% if user.is_staff %}
            <a href="{% url 'socio:listasocio' %}" class="dropdown-item">Añadir clientes</a>
            {% endif %}
            <a href="{% url 'usuario:logout' %}" class="dropdown-item btn-danger" type="submit"><u>Cerrar
              sesión</u></a>
          </div>
        </div>
        {% else %}
        <div class="ml-2 p-1">
          <a class="button type1 font-weight-bold" href="{% url 'usuario:login' %}">Iniciar Sesión</a>
        </div>
        {% endif %}
      </div>
    </div>
  </nav>
  {% endblock menu%}
</div>

templates/base/_send_email.html
<form action="{% url 'inicio' %}" method="post" class="form-group">
  <div class="form-group">
    <input type="email" class="form-control" name="mail" placeholder="Email">
  </div>
  <div class="form-group">
    <input type="submit" value="Enviar" class="btn-sm btn btn-info">
  </div>
</form>

templates/base/contactos.html
{% extends 'base/main.html' %}
{% block contenido %}
<h1 class='titulo-contactos'>Hola socio como estas</h1>
<div class='contenido-contactos'>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus voluptatem odit repudiandae commodi quod ut
    assumenda culpa impedit eum quis earum deserunt illum dolores fugiat delectus neque cumque, ipsa aliquid, nisi
    dolorum eaque tempora, dignissimos. Porro, incidunt asperiores similique omnis repellat corporis magni neque ut
    nesciunt non nemo, quae vitae eos magnam suscipit harum dolorem doloremque laboriosam. Alias mollitia repellendus
    cum sit, labore ea voluptas nisi libero quo adipisci voluptates enim atque veniam possimus velit ad inventore itaque
    nesciunt unde quibusdam deleniti in? Quasi, ea obcaecati a ut, voluptatum pariatur dolorum eveniet eligendi minima
    saepe, sequi quos dicta. Ab distinctio consectetur natus, quae sequi unde dignissimos ducimus itaque, laborum
    obcaecati cumque reprehenderit temporibus ipsum facere dolore rerum accusantium! Corrupti unde culpa aspernatur
    illum accusantium.</p>
</div>
{% endblock contenido%}

templates/base/correo.html
{% load inlinecss %}
{% inlinecss "css/correo.css" %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>Cooperativa W - Socio</title>
	</head>
	<body>
		<div class="container-fluid">
			<h3 class="text-info">Hola Socio - {{mail}}, le hacemos aviso.</h3>
			<p>Fue aprobado su solicitud</p>
		</div>
	</body>
</html>
{% endinlinecss %}

templates/base/main.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  {% include "./_head.html" %}
</head>
<body>
<!--ENCABEZADO DE LA PAGINA WEB img-thumbnail img-fluid justify-content-around -->
{% include "./_nabvar.html" %}
<div class="modal fade" id="modal-search">
  <div class="modal-dialog">
    <div class="modal-content">
      <!--CABECERA-->
      <div class="modal-header" style="font-size: 5px;">
        <h4 class="modal-title text-info">Acerca de</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <!--CUERPO-->
      <div class="modal-body">
        Somo una organización con el unico porposito de mejorar el presupuesto del ciudadano.
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="modal-email">
  <div class="modal-dialog">
    <div class="modal-content">
      <!--CABECERA-->
      <div class="modal-header" style="font-size: 5px;">
        <h4 class="modal-title text-info">Enviar Correo</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <!--CUERPO-->
      <div class="modal-body">
        {% include "./_send_email.html" %}
      </div>
    </div>
  </div>
</div>
<!-- Contenido -->
<main role="main" class="container">
  {% if messages %}
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endfor %}
  {% endif %}
  {% block contenido %}
  <header>
    <div class="d-flex flex-column justify-content-center align-items-center border-bottom imagen-aheader"
         style="background-image: url({% static 'img/bgfondo.jpg' %});">
      <h1 class="d-flex titulo_img ">
        COOPERATIVA DE AHORRO Y CRÉDITO WIÑARISUN
      </h1>
      <P class="d-flex color_parrafo">
        Al servicio de la comunidad huamanguina
      </P>
      <a class="button type3 font-weight-bold" href="{% url 'about' %}" type="submit"><u>Conoce más de nosotros</u></a>
    </div>
  </header>
  <section class="content-section">
    <div id="demo" class="carousel slide carousel-fade " data-ride="carousel">
      <ul class="carousel-indicators">
        <li data-target="demo" data-slide-to="0" class="active"></li>
        <li data-target="demo" data-slide-to="1"></li>
      </ul>
      <div class="carousel-inner  container-fluid border-danger">
        <div class="carousel-item active">
          <img class="img-fluid" src="{% static 'img/ayacucho.jpg' %}">
          <div class="carousel-caption" style="color: #0f529e;">
            <h2 class="font-weight-bold">Cooperativa de Ahorro y Crédito Wiñarisun</h2>
            <h5 class="font-weight-bolder text-black-50">Ya contamos con más de 2 sucursales den la ciudad
              de
              Humanaga, lo hacemos por progreso de ustedes</h5>
          </div>
        </div>
        <div class="carousel-item container-fluid img-fluid">
          <img class="img-fluid" src="{% static 'img/plazamayor.jpg' %}">
          <div class="carousel-caption">
            <h2>Ven acercate para poder pertener a la gran familia de Wiñarisun</h2>
            <p>Solo una organización con más de cinco años en la población ayacuchana y somos una
              organización
              de garantina y aseguramos tu progreso</p>
          </div>
        </div>
        <a href="#demo" class="carousel-control-prev" data-slide="prev"><span class="carousel-control-prev-icon"></span></a>
        <a href="#demo" class="carousel-control-next" data-slide="next"><span class="carousel-control-next-icon"></span></a>
      </div>
    </div>
  </section>
  <br>
  {% endblock %}
</main>
<footer>
  <div class="copyright_row">
    <div class="container">
      <div class="row-footer">
        <div>
          <a href="https://www.facebook.com/" type="submit"><img class="btn-outline-primary"
                                                                 src="{% static 'img/fb.jpg' %}"
                                                                 alt="coopwiñarisun"></a>
        </div>
        <small>Copyright © 2019 Cooperativa Wiñarisun Derechos Reservados <a href="{% url 'inicio' %}"
                                                                             title='https://wiñarisun.aya.pe'>coopwiñarisun</a></small>
      </div>
    </div>
  </div>
</footer>
</body>
</html>

templates/base/mainPrestamos.html
{% extends 'base/main.html' %}
{% block titulo %}Prestamos Socio{% endblock titulo %}
{% block contenido %}
{% endblock contenido %}