WFinanciera/urls.py
from django.contrib import admin
from django.http import HttpRequest
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from apps.usuario import views as views_root

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sobre-nosotros/', views_root.about, name='about'),
    path('', views_root.home, name='inicio'),
    path('partners/', include('apps.socios.urls')),
    path('loans/', include('apps.prestamos.urls')),
    path('accounts/', include('apps.usuario.urls')),
]

apps/socios/urls.py
from django.urls import path
from .views import (
    SocioCreateView,
    SocioDetailView,
    SocioListView,
    SocioEditView,
    SocioDeleteView,
    AccountBankDetailView,
    search_partners,
)

app_name = 'socio'
urlpatterns = [
    path('create-partner/', SocioCreateView.as_view(), name='crearsocio'),
    path('lists-partners/', SocioListView.as_view(), name='listasocio'),
    path('edit-partner/<int:pk>', SocioEditView.as_view(), name='editarsocio'),
    path('delete-partner/<int:pk>',
         SocioDeleteView.as_view(), name='eliminarsocio'),
    path('detail-partner/<int:pk>', SocioDetailView.as_view(), name='detallesocio'),
    path('<int:pk>/account-partner/',
         AccountBankDetailView.as_view(), name='account_bank'),
    path('search-partners/', search_partners, name='search-partners')
]

apps/usuario/urls.py
from django.urls import path
from .views import AccountDetailView, LoginFormView, logout_usuario

app_name = 'usuario'
urlpatterns = [
	path('partners/<int:pk>/', AccountDetailView.as_view(), name='perfilusuario'),
	path('partners/login/',LoginFormView.as_view(), name='login'),
	path('partners/logout/', logout_usuario, name='logout'),
]

apps/socios/models.py
import os

from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.db import models

from ..usuario.models import User


# Create your models here.

# Create of Socio


class Socio(models.Model):
    ELECCION_GENERO = (
        ('F', 'Femenino'),
        ('M', 'Masculino'),
    )

    ESTADO = (
        (True, 'Activo'),
        (False, 'Desactivado'),
    )

    id = models.BigAutoField(primary_key=True)
    nombre = models.CharField(
        'Nombre(s)', max_length=100, blank=False, null=False)
    apellido_paterno = models.CharField(
        'Apellido Paterno', max_length=60, blank=False, null=False)
    apellido_materno = models.CharField(
        'Apellido Materno', max_length=60, blank=False, null=False)
    email = models.EmailField('Email', unique=True, blank=False, null=False)
    dni = models.CharField('DNI', blank=False, null=False, unique=True,
                           max_length=8, validators=[RegexValidator(r'^\d{0,10}$')])
    genero = models.CharField('Género', max_length=1,
                              blank=False, null=False, choices=ELECCION_GENERO)
    fecha_nacimiento = models.DateField('Fecha de nacimiento', auto_now=False)
    telefono = models.CharField('Teléfono', max_length=9, unique=False,
                                blank=True, null=True, validators=[RegexValidator(r'^\d{0,10}$')])
    estado = models.BooleanField('Estado', default=True, choices=ESTADO)
    fb = models.URLField('Facebook', unique=True, blank=True, null=True)
    # Atributtes of class Socio -> Data of location
    fecha_registro = models.DateTimeField(
        'Fecha de registro', auto_now_add=True)
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, unique=True, related_name='socio')

    class Meta:
        ordering = ['id']
        verbose_name = 'Socio'
        verbose_name_plural = 'Socios'
        db_table = 'socios'
        # app_label = 'wfinanciera'

    def __str__(self):
        return "Socio %s" % (self.dni)

    def clean(self):
        if self.email == os.environ.get('MAIL_ADMIN'):
            raise ValidationError('Este email no esta permitido.')

    def get_absolute_url(self):
        from django.shortcuts import reverse

        return reverse('socio:detallesocio', kwargs={'pk': self.id})

    @property
    def is_prestamos_max(self):
        return self.prestamos.count() == 3


class CuentaAhorro(models.Model):
    id = models.BigAutoField(primary_key=True, unique=True)
    monto_cuenta = models.DecimalField(
        'Monto en Cuenta', max_digits=19, decimal_places=2, default=0)
    fecha_retiro = models.DateTimeField('Fecha de registro', auto_now=True)
    socio = models.OneToOneField(
        Socio, on_delete=models.CASCADE, unique=True, related_name='cuenta_ahorro')

    class Meta:
        db_table = 'cuenta_ahorros'
        # app_label = 'wfinanciera'

    def __str__(self):
        return "%d" % self.monto_cuenta

    def add_amount_loan_approved(self, amount):
        self.monto_cuenta += amount
        self.save()

apps/socios/forms.py
import os
from django import forms
from django.core.exceptions import NON_FIELD_ERRORS
from .models import Socio


class SocioForm(forms.ModelForm):
    class Meta:
        model = Socio

        fields = [
            'nombre',
            'apellido_paterno',
            'apellido_materno',
            'dni',
            'genero',
            'fecha_nacimiento',
            'telefono',
            'email',
            'fb',
        ]

        labels = {
            'nombre': 'Nombre(s)',
            'apellido_paterno': 'Apellido Paterno',
            'apellido_materno': 'Apellido Materno',
            'dni': 'DNI',
            'genero': 'Género',
            'fecha_nacimiento': 'Fecha de Nacimiento',
            'telefono': 'Número de celular',
            'email': 'Email',
            'fb': 'Facebook',
        }
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Digíte sus nombres'}),
            'apellido_paterno': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Digite su apellido paterno'}),
            'apellido_materno': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Digite su apellido materno'}),
            'dni': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Digite su Documento Nacional de Identidad',
                       'id': 'dni_socio'}),
            'genero': forms.Select(attrs={'class': 'form-control'}),
            'fecha_nacimiento': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Digite solo números'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Ejemplo socio@mail.com'}),
            'fb': forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'Copie la URL de su facebook'}),
        }

        error_messages = {
            NON_FIELD_ERRORS: {

                'nombre': {
                    'required': 'Por favor introduzca un nombre válido.'
                },
                'dni': {
                    'required': 'Por favor in introduzca un número de DNI válido.',
                },
                'email': {
                    'required': 'Por favor registre un email.',
                    'invalid': 'Este Email no esta permitido.',
                }
            }
        }

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')

        if email == os.environ.get('MAIL_ADMIN'):
            raise forms.ValidationError('Este Email no esta permitido.')

apps/socios/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.db.models import Q

from django.contrib.auth.decorators import login_required

from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from django.views.decorators.csrf import csrf_protect

from django.urls import reverse_lazy

from ..usuario.models import User

from .mixins import SuperUserAndLoginMixin, BankAccountPassesTestMixin, ValidatePermissionStaffMixin, messages
from .forms import SocioForm
from .models import Socio, CuentaAhorro


# Create your views here.
# ------------------------


class SocioCreateView(SuperUserAndLoginMixin, ValidatePermissionStaffMixin, CreateView):
    model = Socio
    form_class = SocioForm
    template_name = 'apps/socios/crearSocio.html'
    success_url = reverse_lazy('socio:listasocio')
    permission_required = 'socio:crearsocio'

    def get_context_data(self, **kwargs):
        context = super(SocioCreateView, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        if form.is_valid():

            user = User(
                username=request.POST['dni'], email=request.POST['email'])
            user.set_password(request.POST['dni'].strip())
            user.save()
            form.instance.user_id = user.id
            form.instance.nombre = request.POST['nombre'].capitalize()
            form.instance.apellido_paterno = request.POST['apellido_paterno'].upper(
            )
            form.instance.apellido_materno = request.POST['apellido_materno'].upper(
            )
            form.save()
            messages.success(request, 'Se ha registrado un nuevo Socio.')
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))


class SocioListView(SuperUserAndLoginMixin, ValidatePermissionStaffMixin, ListView):
    model = Socio
    template_name = 'apps/socios/listaSocio.html'
    context_object_name = 'socios'
    permission_required = 'socio:listasocio'


class SocioEditView(SuperUserAndLoginMixin, ValidatePermissionStaffMixin, UpdateView):
    model = Socio
    form_class = SocioForm
    context_object_name = 'socio'
    permission_required = 'socio:editarsocio'
    template_name = 'apps/socios/editarSocio.html'
    success_url = reverse_lazy('socio:listasocio')

    def get_context_data(self, **kwargs):
        context = super(SocioEditView, self).get_context_data(**kwargs)

        pk = self.kwargs.get('pk', 0)
        socio = self.model.objects.get(id=pk)
        user = self.second_model.objects.get(pk=socio.user_id)

        if 'form' not in context:
            context['form'] = self.form_class()

        return context


class SocioDeleteView(SuperUserAndLoginMixin, ValidatePermissionStaffMixin, DeleteView):
    model = Socio
    permission_required = 'socio:eliminarsocio'
    template_name = 'apps/socios/eliminarSocio.html'
    success_url = reverse_lazy('socio:listasocio')


class SocioDetailView(SuperUserAndLoginMixin, ValidatePermissionStaffMixin, DetailView):
    model = Socio
    template_name = 'apps/socios/socio_detail.html'
    permission_required = 'socio:detallesocio'
    context_object_name = 'socio'

    # Override
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        prestamos_aprobados = self.get_object().prestamos.filter(is_approved=True).all()
        prestamos_en_espera = self.get_object().prestamos.filter(is_approved=False).all()

        context['prestamos_aprobados'] = prestamos_aprobados
        context['prestamos_en_espera'] = prestamos_en_espera
        return context


class AccountBankDetailView(BankAccountPassesTestMixin, DetailView):
    model = CuentaAhorro
    context_object_name = 'bank_account'
    template_name = 'apps/bank_account/show.html'


@csrf_protect
@login_required
def search_partners(request):
    if request.method == 'GET':
        query = request.GET['query'].strip()
        resp = Socio.objects.filter(
            Q(dni=query)
        ).first()

        try:
            context = dict(socios=[resp])
        except:
            messages.error(request, 'Por favor no inserte ningun espacio')
            context = dict()

        return render(request, 'apps/socios/listaSocio.html', context=context)

templates/apps/socios/_search_form.html
<form action="{% url 'socio:search-partners' %}" method="get" class="my-4">
	<h6 class="text-secondary">Buscar de acuerdo al DNI del Socio registrado</h6>
	<div class="form-row">
		<div class="col-sm-5">
			<input type="text" class="form-control" name="query" required>
		</div>
		<div class="col-sm-5">
			<input type="submit" value="Buscar" class="btn-sm btn btn-primary">
		</div>
	</div>
</form>

templates/apps/socios/crearSocio.html
{% extends 'base/main.html' %}

{% block titulo %}Registro de Nuevo Socio{% endblock titulo %}
{% block contenido %}
<div class="container mt-4 pt-2">
	<form method="POST" class="container" action="{% url 'socio:crearsocio' %}">
		{% csrf_token %}
		<div class="container-lg px-lg-5">
			<h2 class="text-info">Registro de Nuevo Socio</h2>
			{% include "apps/partials/_links.html" %}
				<div class="row justify-content-md-start">
					<div class="col-md-4">
						<div class="form-group">
							<label class="text-secondary" for="{{ form.nombre.name }}"> {{form.nombre.label}} </label>
							{% if form.nombre.errors %}
								{{ form.nombre }}
								{% for error in form.nombre.errors %}
									<div class="invalid-feedback">
										{{ error | escape }}
									</div>
								{% endfor %}
							{% else %}
							{{ form.nombre}}
							{% endif %}
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-group">
							<label class="text-secondary" for="{{ form.apellido_paterno.name }}"> {{form.apellido_paterno.label}} </label>
							{{ form.apellido_paterno}}
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-group">
							<label class="text-secondary" for="{{ form.apellido_materno.name }}"> {{form.apellido_materno.label}} </label>
							{{ form.apellido_materno}}
						</div>
					</div>
				</div>
				<div class="row justify-content-md-start">
					<div class="col-md-4">
						<div class="form-group">
							<label class="text-secondary" for="{{ form.dni.name }}"> {{form.dni.label}} </label>
							{% if form.dni.errors %}
								<input type="text" class="form-control is-invalid" required="" maxlength="8" name="dni">
								{% for error in form.dni.errors %}
									<div class="invalid-feedback">
										{{ error | escape}}
									</div>
								{% endfor %}
							{% else %}
								{{ form.dni }}
							{% endif %}

							<small class="small" style="color:rgba(145, 145, 71, 0.812)">Esto servira como el login del Socio</small>
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-group">
							<label class="text-secondary" for="{{ form.genero.name }}"> {{form.genero.label}} </label>
							{{ form.genero }}
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-group">
							<label class="text-secondary" for="{{ form.fecha_nacimiento.name }}"> {{form.fecha_nacimiento.label}}</label>
							{{ form.fecha_nacimiento}}
						</div>
					</div>
				</div>
			<div class="row justify-content-md-start">
				<div class="col-md-4">
					<div class="form-group">
						<label class="text-secondary" for="{{ form.email.name }}">{{form.email.label}}</label>
						{% if form.email.errors %}
							<input type="email" name="email" class="form-control is-invalid" placeholder="Ejemplo socio@mail.com" required>
							{% for error in form.email.errors %}
								<div class="invalid-feedback">
									{{ error | escape }}
								</div>
							{% endfor %}
						{% else %}
							{{ form.email }}
						{% endif %}
					</div>
				</div>
				<div class="col-md-4">
					<div class="form-group">
							<label class="text-secondary" for="{{ form.telefono.name }}"> {{form.telefono.label}} </label>
							{{ form.telefono }}
					</div>
				</div>
			</div>
			<div class="row justify-content-md-start">
				<div class="col-md-4">
					<div class="form-group my-3">
						<input type="submit" class="btn btn-primary" value="Guardar el registro">
						<a href="{% url 'socio:listasocio' %}" class="btn btn-secondary">Salir de Registro</a>
					</div>
				</div>
			</div>
		</div>
	</form>
</div>
{% endblock contenido %}

templates/apps/socios/editarSocio.html
{% extends 'base/main.html' %}

{% block titulo %}Editar perfil del Socio {% endblock titulo %}

{% block contenido %}

<div class="container">
  <form method="post">
    {% csrf_token %}
    <h3 class="text-secondary">Editar datos del Socio <strong>{{socio.nombre}} {{socio.apellido_paterno}} {{socio.apellido_materno}}</strong> </h3>
    <div class="border-2">
      <div class="row justify-content-md-start">
        <div class="col-md-4">
          <label for="{{ form.nombre.name }}"> {{form.nombre.label}} </label>
          {{ form.nombre }}
        </div>
        <div class="col-md-4">
          <label for="{{ form.apellido_paterno.name }}"> {{form.apellido_paterno.label}} </label>
          {{ form.apellido_paterno }}
        </div>
        <div class="col-md-4">
          <label for="{{ form.apellido_materno.name }}"> {{form.apellido_materno.label}} </label>
          {{ form.apellido_materno }}
        </div>
      </div>
        <br>
        <div class="row justify-content-md-start">
          <div class="col-md-4">
            <label for="{{ form.dni.name }}"> {{form.dni.label}} </label>
            {{ form.dni }}
          </div>
          <div class="col-md-4">
            <label for="{{ form.genero.name }}"> {{form.genero.label}} </label>
            {{ form.genero }}
          </div>
          <div class="col-md-4">
            <label for="{{ form.fecha_nacimiento.name }}"> {{form.fecha_nacimiento.label}} </label>
            {{ form.fecha_nacimiento }}
          </div>
        </div>
        <br>
      <div class="row justify-content-md-start">
        <div class="col-md-4">
          <label for="{{ form.telefono.name }}"> {{form.telefono.label}} </label>
          {{ form.telefono }}
        </div>
        <div class="col-md-4">
          <label for="{{ form.email.name }}"> {{form.email.label}} </label>
          {{ form.email }}
        </div>
        <div class="col-md-4">
          <label for="{{ form.fb.name }}"> {{form.fb.label}} </label>
          {{ form.fb }}
        </div>
      </div>
    </div>
    <br>
    <div class="col col-sm-4 col-md-8 col-lg-10 col-xl-12">
      <div class="row justify-content-between">
        <div class="form-group">
          <div class="justify-content-end">
            <button class="btn btn-outline-primary" type="submit">Guardar cambios</button>
          </div>
        </div>
        <div class="form-group">
          <div class="justify-content-start">
           <a href="{% url 'listasocio'%}" class="btn btn-outline-secondary" type="submit">Regresar</a>
          </div>
        </div>
      </div>
    </div>
  </form>
</div>

{% endblock contenido %}

templates/apps/socios/eliminarSocio.html
{% extends 'base/main.html' %}
{% block titulo %}Eliminar socio{% endblock titulo %}
{% block menu %} {% endblock menu %}

{% block contenido %}

<div style="margin: 2em 3.7em 0em; padding: 2rem;">
    <h4>Esta seguro de eliminar al socio <strong style="color: saddlebrown;">
            {{ object.nombre }} {{ object.apellido_paterno }} {{ object.apellido_materno }}</strong></h4>
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsa soluta quam sapiente maxime sed repudiandae voluptatem suscipit, voluptatum amet sint mollitia libero quia vitae pariatur inventore corporis earum, tempore omnis?</p>
</div>

<form method="POST">

    {% csrf_token %}
    {{ form.as_p }}

    <div style="margin-left: 7em;">
        <button type="button" style="margin: 1em 2em ; box-sizing: content-box;" class="btn btn-danger col-sm-1"
            data-toggle="modal" data-target="#eliminar">Si, Eliminar</button>

        <a class="btn btn-primary" style="margin: 1em 2em ; box-sizing: content-box;"
            href="{% url 'listasocio' %}">Cancelar la eliminación</a>
    </div>
    <div class="modal fade" id="eliminar">
        <div class="modal-dialog">
            <div class="modal-content">
                <!--CABECERA-->
                <div class="modal-header">
                    <h5 class="modal-title danger" style="color: darkorange;">Confirmación</h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    Se eliminara al socio <strong>{{ object.nombre }} {{ object.apellido_paterno }}
                        {{ object.apellido_materno }}</strong>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-outline-danger">Confirmar la eliminación</button>
                </div>
            </div>
        </div>
    </div>
</form>


{% endblock contenido %}

templates/apps/socios/listaSocio.html
{% extends 'base/main.html' %}
{% block titulo %}Lista de Socios{% endblock titulo %}
{% block contenido %}
<div class="container-xl  my-4">
	<div class="text-center">
		<h2 class="text-secondary">Formulario de Socios Registrados</h2>
	</div>
	<div class="col col-sm-12 col-xl-12">
		{% include "apps/partials/_links.html" %}
		{% include "./_search_form.html" %}
		<table class="table table-bordered table-hover bg-light">
			<thead class="thead-dark">
				<th style="color: #c5c19bfd;">Nombres</th>
				<th style="color: #c5c19bfd;">Apellido Paterno</th>
				<th style="color: #c5c19bfd;">Apellido Materno</th>
				<th style="color: #c5c19bfd;">DNI</th>
				<th style="color: #c5c19bfd;">Fecha de Nacimiento</th>
				<th style="color: #c5c19bfd;">Teléfono</th>
				<th style="color: #c5c19bfd;">Fecha de Registro</th>
				<th class="text-secondary"></th>
			</thead>

			<div class="overflow-auto">
				{% if socios %}
				{% for socio in socios %}
				<tbody>
					<td>{{ socio.nombre }}</td>
					<td>{{ socio.apellido_paterno }}</td>
					<td>{{ socio.apellido_materno }}</td>
					<td class="text-info">{{ socio.dni }}</td>
					<td>{{ socio.fecha_nacimiento }}</td>
					<td>{% if socio.telefono %}{{ socio.telefono }}{% else %} - {% endif %}</td>
					<td>{{ socio.fecha_registro }}</td>
					<td>
						<a class="btn btn-outline-secondary" href="{% url 'socio:detallesocio' socio.id %}">Ver Detalles</a>
					</td>
				</tbody>
			</div>
			{% endfor %}
			{% endif %}
		</table>

		<div class="form-group">
			<a class="btn btn-success" href="{% url 'socio:crearsocio' %}">Registrar nuevo Socio</a>
			<a class="btn btn-warning" href="{% url 'usuario:perfilusuario' request.user.id %}">Regresar</a>
		</div>
	</div>
</div>
{% endblock contenido %}

templates/apps/socios/socio_detail.html
{% extends 'base/main.html' %}

{% block titulo %} Socio - {{ socio.nombre }} {% endblock titulo %}

{% block contenido %}
<div class="container my-4">
	<div class="row">
		<div class="col-md-7">
			<div class="card">
				<div class="card-body">
					<div class="card-title">
						<h5><b class="text-info">Nombre del Socio:</b> {{ socio.nombre }}</h5>
					</div>
					<div class="card-text">
						<h6><b class="text-info">Apellido Paterno:</b> {{ socio.apellido_paterno }}</h6>
						<h6><b class="text-info">Apellido Materno:</b> {{ socio.apellido_materno }}</h6>

					</div>
				</div>
			</div>

		</div>
		<div class="col-md-5">
			{% if prestamos_aprobados %}
				<h4 class="text-primary">Préstamos Solicitados Aprobados</h4>
				{% for prestamo in prestamos_aprobados %}
					<div class="card-body shadow focus-prestamo">
						<div class="card-title">
							<b>Monto solicitado:</b> <span class="money">{{ prestamo.monto_consulta }}</span>
						</div>
						<div class="card-text">
							{{ prestamo.razon_prestamo | safe }}
						</div>
						<div>
							<b>Solicitud:</b> {% if prestamo.approved %}<span class="text-success">Aprobado</span>
							{% else %}<span class="text-warning">Aun por Aprobar</span>{% endif %}
						</div>
						<div class="text-muted small">
							<b>Fecha de emisión:</b> {{ prestamo.fecha_solicitud_prestamo }}
						</div>
					</div>
				{% endfor %}
			{% endif %}
			{% if prestamos_en_espera %}
				<h4 class="text-secondary">Préstamos Solicitados En Aprobación</h4>
				{% for prestamo in prestamos_en_espera %}
					<div class="card-body shadow focus-prestamo-wait">
						<div class="card-title">
							<b>Monto solicitado:</b> <span class="money">{{ prestamo.monto_consulta }}</span>
						</div>
						<div class="card-text">
							{{ prestamo.razon_prestamo | safe }}
						</div>
						<div>
							<b>Solicitud:</b> {% if prestamo.approved %}<span class="text-success">Aprobado</span>
							{% else %}<span class="text-warning">Aun por Aprobar</span>{% endif %}
						</div>
						<div class="text-muted small">
							<b>Fecha de emisión:</b> {{ prestamo.fecha_solicitud_prestamo }}
						</div>
					</div>
				{% endfor %}
			{% endif %}
		</div>
	</div>
</div>
{% endblock contenido %}