WFinanciera/urls.py
from django.contrib import admin
from django.http import HttpRequest
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from apps.usuario import views as views_root

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sobre-nosotros/', views_root.about, name='about'),
    path('', views_root.home, name='inicio'),
    path('partners/', include('apps.socios.urls')),
    path('loans/', include('apps.prestamos.urls')),
    path('accounts/', include('apps.usuario.urls')),
]

apps/prestamos/urls.py
from django.urls import path
from .views import (
	PrestamoListView,
	PrestamoCreateView,
	approved_prestamo,
	cancel_request_loan,
	search_loans
	)

app_name = 'prestamos'
urlpatterns = [
	path('registros_prestamos/',PrestamoListView.as_view(), name ='listaprestamo'),
	path('<int:pk>/solicitar_prestamo/', PrestamoCreateView.as_view(), name='solicitarprestamo'),
	path('<int:id>/approved_prestamo', approved_prestamo,name='approved-prestamo'),
	path('search-loans/', search_loans, name = 'search-loans'),
	path('<int:id>/', cancel_request_loan, name ='cancel_request_loan')
]

apps/socios/urls.py
from django.urls import path
from .views import (
    SocioCreateView,
    SocioDetailView,
    SocioListView,
    SocioEditView,
    SocioDeleteView,
    AccountBankDetailView,
    search_partners,
)

app_name = 'socio'
urlpatterns = [
    path('create-partner/', SocioCreateView.as_view(), name='crearsocio'),
    path('lists-partners/', SocioListView.as_view(), name='listasocio'),
    path('edit-partner/<int:pk>', SocioEditView.as_view(), name='editarsocio'),
    path('delete-partner/<int:pk>',
         SocioDeleteView.as_view(), name='eliminarsocio'),
    path('detail-partner/<int:pk>', SocioDetailView.as_view(), name='detallesocio'),
    path('<int:pk>/account-partner/',
         AccountBankDetailView.as_view(), name='account_bank'),
    path('search-partners/', search_partners, name='search-partners')
]

apps/usuario/urls.py
from django.urls import path
from .views import AccountDetailView, LoginFormView, logout_usuario

app_name = 'usuario'
urlpatterns = [
	path('partners/<int:pk>/', AccountDetailView.as_view(), name='perfilusuario'),
	path('partners/login/',LoginFormView.as_view(), name='login'),
	path('partners/logout/', logout_usuario, name='logout'),
]

apps/prestamos/models.py
from ckeditor.fields import RichTextField
from django.core.exceptions import ValidationError
from django.db import models

from ..socios.models import Socio


# Create your models here.

# CLASE DE PRESTAMOS , PARA CADA OSCIO EN LA SOLICITUD


class Prestamo(models.Model):
    id = models.BigAutoField(primary_key=True)
    ocupacion_socio = models.CharField('Ocupación laboral', max_length=50,
                                       blank=False, null=False, help_text='Profesión en el que se desempeña.')
    monto_consulta = models.DecimalField(
        'Monto a solicitar', blank=False, null=False, max_digits=7, decimal_places=2, default=0)
    razon_prestamo = RichTextField('Razones de Solicitud de préstamo',
                                   help_text='Su razón de solicitud debe de ser los más breve posible.')
    fecha_solicitud_prestamo = models.DateField(
        'Fecha de solicitud', auto_now_add=True)

    fecha_aprobacion_prestamo = models.DateField(
        'Fecha de aprobación', auto_now=False, null=True, blank=True)

    is_approved = models.BooleanField('Aprobado', default=False, null=False)
    socio = models.ForeignKey(
        Socio, on_delete=models.CASCADE, related_name='prestamos')

    class Meta:
        verbose_name = 'Prestamo'
        verbose_name_plural = 'Prestamos'
        db_table = 'prestamos'
        ordering = ['-fecha_solicitud_prestamo']
        # app_label = 'wfinanciera'

    def __str__(self):
        return "Prestamo %s" % self.socio

    @property
    def approved(self):
        return self.is_approved

    @approved.setter
    def approved(self, approved):
        self.is_approved = approved

    @property
    def get_mount_loan(self):
        return self.monto_consulta

    def clean(self):
        if self.monto_consulta > 9999.99:
            raise ValidationError('El monto debe de exceder de 10000 soles')

apps/prestamos/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from .models import Prestamo


class PrestamoForm(forms.ModelForm):
    monto_consulta = forms.DecimalField(
        max_value=4999, min_value=120, max_digits=7, decimal_places=2)

    class Meta:
        model = Prestamo

        fields = ['ocupacion_socio', 'razon_prestamo']

        labels = {
            'ocupacion_socio': 'Ocupación Laboral',
            'razon_prestamo': 'Razón de prestamo',
        }

        widgets = {
            'ocupacion_socio': forms.TextInput(attrs={'class': 'form-control'}),
            'razon_prestamo': CKEditorWidget(attrs={'class': 'form-control', 'id': 'razon'}),
        }

        error_messages = {
            'ocupacion_socio': {
                'invalid': "Debera completar es campo.",
            },
        }

apps/prestamos/views.py
from datetime import datetime
from django.conf import settings
from django.shortcuts import get_object_or_404, HttpResponseRedirect, render
from django.urls import reverse

from django.db.models import Q

from django.contrib import messages
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin
)
from django.contrib.auth.decorators import login_required

from django.views.generic import ListView, CreateView, TemplateView
from django.views.decorators.csrf import csrf_protect

from .models import Prestamo
from .forms import PrestamoForm

from ..socios.models import Socio


# Create your views here.


class PrestamoListView(LoginRequiredMixin, ListView):
    model = Prestamo
    context_object_name = 'prestamos'
    template_name = 'apps/prestamos/listaPrestamo.html'
    ordering = ['-fecha_solicitud_prestamo']
    paginate_by = settings.PAGINATE_BY


class PrestamoCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Prestamo
    template_name = 'apps/prestamos/crearPrestamo.html'
    form_class = PrestamoForm

    def get_context_data(self, **kwargs):
        context = super(PrestamoCreateView, self).get_context_data(**kwargs)
        if self.request.user.socio.is_prestamos_max:
            context['warning'] = "Usted no puede realizar más solicitudes de prestamos."
            return context

        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        if form.is_valid():
            form.instance.monto_consulta = form.cleaned_data.get(
                'monto_consulta', 0.0)
            form.instance.socio = request.user.socio
            form.save()
            messages.success(request, 'Usted acaba de solicitar un préstamo.')
            return HttpResponseRedirect(reverse('usuario:perfilusuario', args=[request.user.id, ]))

        else:
            messages.error(request, 'Revise los errores por favor.')
            return self.render_to_response(self.get_context_data(form=form))

    def test_func(self):
        socio_id = self.kwargs.get('pk', 0)
        if self.request.user.id == int(socio_id):
            return True
        return False


class PrestamoTemplateView(LoginRequiredMixin, TemplateView):
    model = Prestamo
    template_name = 'apps/usuario/prestamoListo.html'


@csrf_protect
@login_required
def approved_prestamo(request, id):
    prestamo = get_object_or_404(Prestamo, id=id)
    prestamo.approved = True
    prestamo.fecha_aprobacion_prestamo = datetime.now()
    prestamo.socio.cuenta_ahorro.add_amount_loan_approved(
        prestamo.monto_consulta)
    prestamo.save()
    messages.info(
        request,
        f'La solicitud del prestamo de {prestamo.socio.nombre} {prestamo.socio.apellido_paterno} {prestamo.socio.apellido_materno} fue aprobado ')
    return HttpResponseRedirect(reverse('prestamos:listaprestamo'))


@csrf_protect
@login_required
def cancel_request_loan(request, id):
    prestamo = get_object_or_404(Prestamo, id=id)
    prestamo.delete()
    messages.warning(request, 'Usted acaba de cancelar su solicitud')
    return HttpResponseRedirect(reverse('usuario:perfilusuario', args=[request.user.id, ]))


@csrf_protect
@login_required
def search_loans(request):
    if request.method == 'GET':
        query = request.GET.get('query')
        resp = Socio.objects.filter(
            Q(dni=query)
        ).first()

        try:
            context = dict(prestamos=resp.prestamos.all())
        except:
            messages.error(request, 'Por favor no inserte ningun espacio')
            context = dict()

        return render(request, 'apps/prestamos/listaPrestamo.html', context=context)

templates/apps/prestamos/_modal_prestamos.html
<!-- Modal -->
<div class="modal fade" id="cancelLoanModalStatis" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="cancelLoanModalStatisLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="cancelLoanModalStatisLabel">Cancelar mi Solicitud</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				¿Esta seguro de poder cancelar su Solicitud?
				<p class="text-info">Monto Solicitado: <span class="money">{{ prestamo.monto_consulta }}</span></p>
				<div class="mt-3">
					<form action="{% url 'prestamos:cancel_request_loan' prestamo.id %}" method="post">
						{% csrf_token %}
						<input type="submit" value="Si, Estoy seguro" class="btn btn-warning">
					</form>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">No, aun quiero mantener mi solicitud</button>
			</div>
		</div>
	</div>
</div>

templates/apps/prestamos/_search_form.html
<form action="{% url 'prestamos:search-loans' %}" method="get" class="my-4">
	<h6 class="text-secondary">Buscar de acuerdo al DNI del Socio registrado</h6>
	<div class="form-row">
		<div class="col-sm-5">
			<input type="text" class="form-control" name="query" required>
		</div>
		<div class="col-sm-5">
			<input type="submit" value="Buscar" class="btn-sm btn btn-primary">
		</div>
	</div>
</form>

templates/apps/prestamos/crearPrestamo.html
{% extends 'base/main.html' %}
{% block titulo %}Solicitar Préstamo{% endblock titulo %}
{% block contenido %}
{% if warning %}
	<div class="col-lg-5">
		<h2>{{ warning }}</h2>
	</div>
{% else %}
	<form method="POST">
		{% csrf_token %}
		<h3>Solicitar préstamo</h3>
		<h5 class="text-info">Por favor llene el formulario, para poder solicitar un préstamo.</h5>
		<div class="row">
			<div class="col-md-4">
				<div class="form-group">
					<label for="prestamisa">Socio</label>
					<h5 class="text-info"><b>{{ user.socio.nombre }} {{ user.socio.apellido_paterno }}{{ user.socio.apellido_materno }}</b></h5>
				</div>
			</div>
			<div class="col-md-4">
				<div class="form-group">
					<label for="{{ form.ocupacion_socio.name }}"> {{form.ocupacion_socio.label}} </label>
					{% if form.ocupacion_socio.errors %}
						<div class="form-group">
							<input name="ocupacion_socio" type="text" class="form-control is-invalid">
						</div>
						{% for error in form.ocupacion_socio.errors %}
							<div class="invalid-feedback">
								{{ error }}
							</div>
						{% endfor %}
					{% else %}
						<div class="form-group">
							{{ form.ocupacion_socio }}
						</div>
					{% endif %}
				</div>
			</div>
			<div class="col-md-4">
				<div class="form-group">
					<label for="{{ form.monto_consulta.name }}"> {{form.monto_consulta.label}} </label>
					{% if form.monto_consulta.errors %}
						<div class="form-group">
							{{form.monto_consulta}}
						</div>
						{% for error in form.monto_consulta.errors %}
							<div class="invalid-feedback">
								{{ error }}
							</div>
						{% endfor %}
					{% else %}
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-prepend">
									<span class="input-group-text">S/</span>
									{{form.monto_consulta}}
								</div>
							</div>
						</div>
					{% endif %}
					<p class="small text-muted"><span class="text-warning">Nota: </span><br>Por favor el monto a solicitar de ser menor a <strong>9999.99</strong></p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<label for="{{ form.razon_prestamo.name }}"> {{form.razon_prestamo.label}} </label>
					{{ form.razon_prestamo}}
					<p class="text-secondary">{{ form.razon_prestamo.help_text }}</p>
				</div>
				<div class="form-group">
					<button type="submit" class="btn btn-primary" onclick="aviso()">Solicitar Prestamo</button>
				</div>
				<div class="form-group">
					<div class="col-auto"><a href="{% url 'usuario:perfilusuario' user.id %}" class="btn btn-dark">Atrás</a></div>
				</div>
			</div>
			<div class="col-md-6">
			</div>
		</div>
	</form>
{% endif %}
{% endblock contenido %}

templates/apps/prestamos/listaPrestamo.html
{% extends 'base/main.html' %}
{% block titulo %} Formulario de prestamos {% endblock titulo %}
{% block contenido %}
<div class="container">
	<div class="row">
		<div class="text-center">
			<h2>Formulario de Solicitudes de Prestamos</h2>
		</div>
		<div class="col col-sm-12 col-xl-12">
			{% include "apps/partials/_links.html" %}
			{% include "./_search_form.html" %}
			<table class="table table-hover">
				<thead class="thead-dark">
					<th style="color: #c5c19bfd;">Socio</th>
					<th style="color: #c5c19bfd;">DNI del Solicitante(Socio)</th>
					<th style="color: #c5c19bfd;">Ocupación/Profesión</th>
					<th style="color: #c5c19bfd;">Monto solicitado</th>
					<th style="color: #c5c19bfd;">Razón Solicitud de prestamo</th>
					<th style="color: #c5c19bfd;">Fecha de Solicitud</th>
					<th style="color: #c5c19bfd;">Préstamo Aprobado</th>
				</thead>
				<div class="overflow-auto">
					{% if prestamos %}
					{% for prestamo in prestamos %}
					<tr>
						<td><a href="{% url 'socio:detallesocio' prestamo.socio.id %}">{{ prestamo.socio.nombre }}
								{{ prestamo.socio.apellido_paterno }} {{ prestamo.socio.apellido_materno }}</a></td>
						<td>{{ prestamo.socio.dni }}</td>
						<td>{{ prestamo.ocupacion_socio }}</td>
						<td><span class="money">{{ prestamo.monto_consulta }}</span></td>
						<td>{{ prestamo.razon_prestamo | safe | truncatechars:20c}}</td>
						<td>{{ prestamo.fecha_solicitud_prestamo }}</td>
						{% if prestamo.approved %}<td class="text-success">Aprobado</td>{% else %}<td class="text-danger">Solicitud
							entregada</td>{% endif %}
						{% if not prestamo.approved %}
						<td colspan="2">
							<form action="{% url 'prestamos:approved-prestamo' prestamo.id %}" method="post">{% csrf_token %}<input
									class="btn btn-success btn-block" type="submit" value="Aprobar al solicitud"></form>
						</td>
						{% endif %}
					</tr>
					{% endfor %}
				</div>
				{% else %}
				<h5>No se encontro ninguna Solicitud de Préstamo</h5>
				{% endif %}
			</table>
		</div>
	</div>
	<div class="pagination">
		<span class="step-links">
			{% if page_obj.has_previous %}
			<a href="?page=1">&laquo; first</a>
			<a href="?page={{ page_obj.previous_page_number }}">previous</a>
			{% endif %}
			<span class="current">
				Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
			</span>
			{% if page_obj.has_next %}
			<a href="?page={{ page_obj.next_page_number }}">next</a>
			<a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
			{% endif %}
		</span>
	</div>
</div>
{% endblock contenido %}

templates/apps/prestamos/prestamoGarante.html
{% extends 'base/main.html' %}
{% block titulo %}Prestamo con Garante{% endblock titulo %}
{% block menu %}{% endblock menu %}
{% block contenido %}
<form method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<button class="form-control" type="submit">Solicitar prestamo</button>
</form>
{% endblock contenido %}