WFinanciera/urls.py
from django.contrib import admin
from django.http import HttpRequest
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from apps.usuario import views as views_root

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sobre-nosotros/', views_root.about, name='about'),
    path('', views_root.home, name='inicio'),
    path('partners/', include('apps.socios.urls')),
    path('loans/', include('apps.prestamos.urls')),
    path('accounts/', include('apps.usuario.urls')),
]

apps/prestamos/urls.py
from django.urls import path
from .views import (
	PrestamoListView,
	PrestamoCreateView,
	approved_prestamo,
	cancel_request_loan,
	search_loans
	)

app_name = 'prestamos'
urlpatterns = [
	path('registros_prestamos/',PrestamoListView.as_view(), name ='listaprestamo'),
	path('<int:pk>/solicitar_prestamo/', PrestamoCreateView.as_view(), name='solicitarprestamo'),
	path('<int:id>/approved_prestamo', approved_prestamo,name='approved-prestamo'),
	path('search-loans/', search_loans, name = 'search-loans'),
	path('<int:id>/', cancel_request_loan, name ='cancel_request_loan')
]

apps/socios/urls.py
from django.urls import path
from .views import (
    SocioCreateView,
    SocioDetailView,
    SocioListView,
    SocioEditView,
    SocioDeleteView,
    AccountBankDetailView,
    search_partners,
)

app_name = 'socio'
urlpatterns = [
    path('create-partner/', SocioCreateView.as_view(), name='crearsocio'),
    path('lists-partners/', SocioListView.as_view(), name='listasocio'),
    path('edit-partner/<int:pk>', SocioEditView.as_view(), name='editarsocio'),
    path('delete-partner/<int:pk>',
         SocioDeleteView.as_view(), name='eliminarsocio'),
    path('detail-partner/<int:pk>', SocioDetailView.as_view(), name='detallesocio'),
    path('<int:pk>/account-partner/',
         AccountBankDetailView.as_view(), name='account_bank'),
    path('search-partners/', search_partners, name='search-partners')
]

apps/usuario/urls.py
from django.urls import path
from .views import AccountDetailView, LoginFormView, logout_usuario

app_name = 'usuario'
urlpatterns = [
	path('partners/<int:pk>/', AccountDetailView.as_view(), name='perfilusuario'),
	path('partners/login/',LoginFormView.as_view(), name='login'),
	path('partners/logout/', logout_usuario, name='logout'),
]

apps/prestamos/models.py
from ckeditor.fields import RichTextField
from django.core.exceptions import ValidationError
from django.db import models

from ..socios.models import Socio


# Create your models here.

# CLASE DE PRESTAMOS , PARA CADA OSCIO EN LA SOLICITUD


class Prestamo(models.Model):
    id = models.BigAutoField(primary_key=True)
    ocupacion_socio = models.CharField('Ocupación laboral', max_length=50,
                                       blank=False, null=False, help_text='Profesión en el que se desempeña.')
    monto_consulta = models.DecimalField(
        'Monto a solicitar', blank=False, null=False, max_digits=7, decimal_places=2, default=0)
    razon_prestamo = RichTextField('Razones de Solicitud de préstamo',
                                   help_text='Su razón de solicitud debe de ser los más breve posible.')
    fecha_solicitud_prestamo = models.DateField(
        'Fecha de solicitud', auto_now_add=True)

    fecha_aprobacion_prestamo = models.DateField(
        'Fecha de aprobación', auto_now=False, null=True, blank=True)

    is_approved = models.BooleanField('Aprobado', default=False, null=False)
    socio = models.ForeignKey(
        Socio, on_delete=models.CASCADE, related_name='prestamos')

    class Meta:
        verbose_name = 'Prestamo'
        verbose_name_plural = 'Prestamos'
        db_table = 'prestamos'
        ordering = ['-fecha_solicitud_prestamo']
        # app_label = 'wfinanciera'

    def __str__(self):
        return "Prestamo %s" % self.socio

    @property
    def approved(self):
        return self.is_approved

    @approved.setter
    def approved(self, approved):
        self.is_approved = approved

    @property
    def get_mount_loan(self):
        return self.monto_consulta

    def clean(self):
        if self.monto_consulta > 9999.99:
            raise ValidationError('El monto debe de exceder de 10000 soles')

apps/usuario/models.py
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
    Group
)
from django.db import models
from django.utils import timezone


class UserManager(BaseUserManager):

    def create_user(self, username, email, password=None):
        if not email:
            raise ValueError('User has an email.')
        if not username:
            raise ValueError('User has an username')

        user = self.model(
            username=username,
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
        )
        user.set_password(password)
        user.is_staff = True
        user.is_admin = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField('Username', max_length=50, unique=True)
    email = models.EmailField('Email', max_length=100, unique=True)
    date_joined = models.DateTimeField(default=timezone.now)
    is_staff = models.BooleanField('Staff', default=False)
    is_admin = models.BooleanField('Admin', default=False)
    is_active = models.BooleanField('Active', default=True)
    groups = models.ManyToManyField(Group)
    objects = UserManager()

    class Meta:
        db_table = 'users'

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', ]

    def __str__(self):
        return "<User %s>" % self.username

apps/prestamos/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from .models import Prestamo


class PrestamoForm(forms.ModelForm):
    monto_consulta = forms.DecimalField(
        max_value=4999, min_value=120, max_digits=7, decimal_places=2)

    class Meta:
        model = Prestamo

        fields = ['ocupacion_socio', 'razon_prestamo']

        labels = {
            'ocupacion_socio': 'Ocupación Laboral',
            'razon_prestamo': 'Razón de prestamo',
        }

        widgets = {
            'ocupacion_socio': forms.TextInput(attrs={'class': 'form-control'}),
            'razon_prestamo': CKEditorWidget(attrs={'class': 'form-control', 'id': 'razon'}),
        }

        error_messages = {
            'ocupacion_socio': {
                'invalid': "Debera completar es campo.",
            },
        }

apps/usuario/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm


class FormularioLogin(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(FormularioLogin, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['class'] = 'form-control'

apps/prestamos/views.py
from datetime import datetime
from django.conf import settings
from django.shortcuts import get_object_or_404, HttpResponseRedirect, render
from django.urls import reverse

from django.db.models import Q

from django.contrib import messages
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin
)
from django.contrib.auth.decorators import login_required

from django.views.generic import ListView, CreateView, TemplateView
from django.views.decorators.csrf import csrf_protect

from .models import Prestamo
from .forms import PrestamoForm

from ..socios.models import Socio


# Create your views here.


class PrestamoListView(LoginRequiredMixin, ListView):
    model = Prestamo
    context_object_name = 'prestamos'
    template_name = 'apps/prestamos/listaPrestamo.html'
    ordering = ['-fecha_solicitud_prestamo']
    paginate_by = settings.PAGINATE_BY


class PrestamoCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Prestamo
    template_name = 'apps/prestamos/crearPrestamo.html'
    form_class = PrestamoForm

    def get_context_data(self, **kwargs):
        context = super(PrestamoCreateView, self).get_context_data(**kwargs)
        if self.request.user.socio.is_prestamos_max:
            context['warning'] = "Usted no puede realizar más solicitudes de prestamos."
            return context

        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        if form.is_valid():
            form.instance.monto_consulta = form.cleaned_data.get(
                'monto_consulta', 0.0)
            form.instance.socio = request.user.socio
            form.save()
            messages.success(request, 'Usted acaba de solicitar un préstamo.')
            return HttpResponseRedirect(reverse('usuario:perfilusuario', args=[request.user.id, ]))

        else:
            messages.error(request, 'Revise los errores por favor.')
            return self.render_to_response(self.get_context_data(form=form))

    def test_func(self):
        socio_id = self.kwargs.get('pk', 0)
        if self.request.user.id == int(socio_id):
            return True
        return False


class PrestamoTemplateView(LoginRequiredMixin, TemplateView):
    model = Prestamo
    template_name = 'apps/usuario/prestamoListo.html'


@csrf_protect
@login_required
def approved_prestamo(request, id):
    prestamo = get_object_or_404(Prestamo, id=id)
    prestamo.approved = True
    prestamo.fecha_aprobacion_prestamo = datetime.now()
    prestamo.socio.cuenta_ahorro.add_amount_loan_approved(
        prestamo.monto_consulta)
    prestamo.save()
    messages.info(
        request,
        f'La solicitud del prestamo de {prestamo.socio.nombre} {prestamo.socio.apellido_paterno} {prestamo.socio.apellido_materno} fue aprobado ')
    return HttpResponseRedirect(reverse('prestamos:listaprestamo'))


@csrf_protect
@login_required
def cancel_request_loan(request, id):
    prestamo = get_object_or_404(Prestamo, id=id)
    prestamo.delete()
    messages.warning(request, 'Usted acaba de cancelar su solicitud')
    return HttpResponseRedirect(reverse('usuario:perfilusuario', args=[request.user.id, ]))


@csrf_protect
@login_required
def search_loans(request):
    if request.method == 'GET':
        query = request.GET.get('query')
        resp = Socio.objects.filter(
            Q(dni=query)
        ).first()

        try:
            context = dict(prestamos=resp.prestamos.all())
        except:
            messages.error(request, 'Por favor no inserte ningun espacio')
            context = dict()

        return render(request, 'apps/prestamos/listaPrestamo.html', context=context)

apps/usuario/views.py
from django.conf import settings

from django.shortcuts import reverse, render
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect

from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

from django.utils.decorators import method_decorator

from django.views.decorators.cache import never_cache
from django.views.generic import FormView, DetailView
from django.views.decorators.csrf import csrf_protect, csrf_exempt

from django.core.mail import EmailMultiAlternatives

from django.template.loader import get_template

from .forms import FormularioLogin
from .mixins import AccountPassesTestMixin, LoginRequiredValidateUserMixin, messages
from .models import User
from ..prestamos.models import Prestamo


class LoginFormView(FormView):
    form_class = FormularioLogin
    template_name = 'apps/usuario/login.html'
    # Se dirige al perfil del usuario logeado
    success_url = reverse_lazy('inicio')

    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(self.get_success_url())
        else:
            return super(LoginFormView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        '''
        Validación del Form, y redireccionamiento del admin al Dashboard
        '''
        login(self.request, form.get_user())

        if self.request.user.is_admin:
            messages.info(self.request, 'Inicio Sesión de Staff')
            return HttpResponseRedirect(reverse('socio:listasocio'))

        messages.info(self.request, 'Inicio Sesión')
        return super(LoginFormView, self).form_valid(form)


@login_required
def logout_usuario(request):
    logout(request)
    return HttpResponseRedirect(reverse_lazy('usuario:login'))


class AccountDetailView(LoginRequiredValidateUserMixin, AccountPassesTestMixin, DetailView):
    model = User
    template_name = 'apps/usuario/account_detail.html'
    context_object_name = 'account'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if not self.request.user.is_admin:
            prestamos_aprobados = Prestamo.objects.filter(
                socio=self.request.user.socio, is_approved=True).all()
            prestamos_en_espera = Prestamo.objects.filter(
                socio=self.request.user.socio, is_approved=False).all()
            context['prestamos_aprobados'] = prestamos_aprobados
            context['prestamos_en_espera'] = prestamos_en_espera
            context['message'] = "<strong>Aviso: </strong>Usted ya no podrá realizar más solicitudes de Prestamo"
            return context
        return context


def send_email(mail):
    context = {'mail': mail}
    template = get_template('base/correo.html')
    content = template.render(context)

    email = EmailMultiAlternatives(
        'Un correo de prueba',
        'Admin W',
        settings.EMAIL_HOST_USER,
        [mail],
    )
    email.attach_alternative(content, 'text/html')
    email.send()


@csrf_exempt
def home(request):
    if request.method == 'POST':
        mail = request.POST['mail']
        send_email(mail)

    return render(request, 'base/main.html')


def about(request):
    return render(request, 'base/contactos.html')

templates/apps/usuario/_prestamos.html
{% if prestamos_aprobados %}
<h5 class="text-primary">Préstamos Aprobados</h5>
{% for prestamo in prestamos_aprobados %}
<div class="card-body focus-prestamo border my-2">
	<div class="card-title">
		<b>Monto solicitado:</b> <span class="money">{{ prestamo.monto_consulta }}</span>
	</div>
	<div>
		<b>Solicitud: </b><span class="text-success">Aprobado</span>
	</div>
	<div class="text-muted small">
		<b style="text-decoration: underline;">Fecha de aprobación:</b> {{ prestamo.fecha_aprobacion_prestamo }}<br>
		<b>Fecha de emisión:</b> {{ prestamo.fecha_solicitud_prestamo }}
	</div>
</div>
{% endfor %}
{% endif %}
{% if prestamos_en_espera %}
<hr>
<h5 class="text-secondary">Prestamos aun en Aprobación</h5>
{% for prestamo in prestamos_en_espera %}
<div class="card-body focus-prestamo-wait border my-2">
	<div class="card-title">
		<div class="row">
			<div class="col-8">
				<b>Monto solicitado: </b><span class="money">{{ prestamo.monto_consulta }}</span>
			</div>
			<div class="col-4">
				<button class="btn btn-outline-danger border-0" data-toggle="modal" data-target="#cancelLoanModalStatis">
					Cancelar Solicitud
				</button>
			</div>
		</div>
	</div>
	<div>
		<b>Solicitud: </b><span class="text-warning">Aun por Aprobar</span>
	</div>
	<div class="text-muted small">
		<b>Fecha de emisión:</b> {{ prestamo.fecha_solicitud_prestamo }}
	</div>
</div>
{% include "../prestamos/_modal_prestamos.html" %}
{% endfor %}
{% endif %}

templates/apps/usuario/account_detail.html
{% extends 'base/main.html' %}
{% load static %}
{% block titulo %}Mi perfil - {{ account.socio.nombre }} {% endblock titulo %}
{% block contenido %}
<div class="container my-2">
	<div class="row">
		<div class="col-md-6">
			<div class="card">
				<div class="card-header">
					<img src="{% static 'img/thumbnail.png' %}" class="img-thumbnail">
				</div>
				<div class="card-body">
					{% if user.is_staff %}
						<p>Estado: <strong style="color: green;">Activo</strong></p>
						<p>Usuario: <strong style="color: red;">Administrador</strong></p>
						<div class="form-group">
							<a class="btn btn-outline-primary" href="{% url 'socio:crearsocio' %}">Crear Nuevos Socios</a>
							<a class="btn btn-outline-secondary" href="{% url 'socio:listasocio' %}">Formulario de Lista de Socios</a>
							<a class="btn btn-outline-primary" href="{% url 'prestamos:listaprestamo' %}">Ver Solicitudes de Préstamos</a>
						</div>
					{% else %}
						<div class="card">
							<div class="row">
								<div class="col-6">
									<h5 class="text-info"><strong>Socio de Wiñarisun</strong></h5>
									<p>Estado: <strong style="color: green;">Activo</strong></p>
									<h5 class="card-text"><strong>Socio:</strong></h5>
									<ul class="info-data-partner">
										<li><b>Nombre:</b> {{ account.socio.nombre }}</li>
										<li><b>Apellido Paterno:</b> {{ account.socio.apellido_paterno}}</li>
										<li><b>Apellido Materno:</b> {{ account.socio.apellido_materno}}</li>
										<li><b>DNI:</b> {{ account.socio.dni }}</li>
										<li><b>Prestamos solicitados: </b> {{ account.socio.prestamos.count }}</li>
									</ul>
								</div>
								<div class="col-6">
									<a href="{% url 'socio:account_bank' request.user.socio.id %}" class="btn btn-sm btn-outline-success btn-block">Mi Cuenta de Ahorro</a>
									<div class="border border-primary p-2 my-2">
										<b>Cuenta en Saldo: </b>S/{{ account.socio.cuenta_ahorro.monto_cuenta }}
									</div>
								</div>
							</div>
						</div>
						{% if not account.socio.is_prestamos_max %}
							<a class="btn btn-outline-primary" href="{% url 'prestamos:solicitarprestamo' user.id %}"> Solicitar Prestamo</a>
						{% else %}
							<div class="alert alert-warning alert-dissmisable fade show" role="alert">
								{{ message | safe }}
								<button type="button" class="close" data-dismiss="alert" aria-label="Close">
								<span aria-hidden="true">&times;</span>
								</button>
							</div>
						{% endif %}
					{% endif %}
				</div>
			</div>
		</div>
		<div class="col-md-6">
			{% include "./_prestamos.html" %}
		</div>
	</div>
</div>
<!-- Button trigger modal -->
{% endblock contenido %}

templates/apps/usuario/login.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
	<head>
		<title>Inicio Sesión - Wiñarisun</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<script src="{% static 'js/jquery.js' %}" defer></script>
		<script src="{% static 'js/popper.js' %}" defer></script>
		<script src="{% static 'js/bootstrap.min.js' %}" defer></script>
		<script src="{% static 'login/js/main.js' %}" defer></script>
		<link rel="stylesheet" type="text/css" href="{% static 'login/css/util.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'login/css/main.css' %}">
		<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css">
	</head>
	<body>
			<form method="post">
				{% csrf_token %}
				<div class="limiter">
					<div class="container-login100 login-page">
						<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-50">
							{% if messages %}
								{% for message in messages %}
									<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
										{{ message }}
										<button type="button" class="close" data-dismiss="alert" aria-label="Close">
										<span aria-hidden="true">&times;</span>
										</button>
									</div>
								{% endfor %}
							{% endif %}
							<span class="login100-form-title p-b-33">
								Inicie Sesión - Socio
							</span>
							{% if form.errors %}
								<div class="alert alert-warning alert-dismissible fade show" role="alert">
									<strong>Advertencia: </strong> {{ form.get_invalid_login_error }}
									<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
									</button>
								</div>
							{% else %}
								<p>Ingrese</p>
							{% endif %}
							<div class="form-group">
								<label for="username" class="label-form">Usuario</label>
								<div class="wrap-input100 validate-input" data-validate="Valid email is required: ex@abc.xyz">
									{{ form.username }}
								</div>
							</div>
							<div class="form-group">
								<label for="password" class="label-form">Contraseña</label>
								{% if form.password.errors %}
									<input type="password" name="password" class="form-control is-invalid" required="" id="id_password">
									{% for error in form.password.errors %}
										<div class="invalid-feedback">
											{{ error }}
										</div>
									{% endfor %}
								{% else %}
									{{ form.password }}
								{% endif %}
							</div>
							<div class="form-group container-login100-form-btn m-t-20">
								<button class="btn btn-outline-primary btn-block" type="submit">
								Iniciar sesión
								</button>
							</div>
							<div class="text-center p-t-45 p-b-4">
								<span class="txt1">
									Ólvido su <a href="#" class="txt2 hov1">
										Usuario / Contraseña ?
									</a>
								</span>
							</div>
						</div>
					</div>
				</div>
			</form>
		</body>
	</html>

templates/apps/usuario/prestamoListo.html
{% extends 'base/main.html' %}

{% block titulo %}Préstamo Realizado{% endblock titulo %}

{% block menu %} {% endblock menu %}

{% block contenido %}

<h1>Felicidades usted acaba de realizar su Préstamo de  {{nombre}} </h1>
{% endblock contenido %}